# Generated by Django 5.2.4 on 2025-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.ImageField(blank=True, upload_to="barcodes/"),
        ),
    ]
